### ISSUE TITLE
Dialog title does not change.

### ISSUE THREAD

**Issue by aslanon** [aslanon/vue-confirm-dialog#2]
**Describe the bug**
If title has not been sent from the option json, it comes to default text

```json
{
  "message": "Are you sure?",
  "auth": false,
  "button": {
    "yes": "OK"
  }
}
```

**Comment by rachitpant** [comment]
The confirm action ( with value false ) is being triggered without clicking anywhere.

![popup issue](https://user-images.githubusercontent.com/1474415/83083161-6b3b4e80-a053-11ea-9a82-cf8317a3b5e6.gif)
